### ISSUE TITLE
Question about update.

### ISSUE THREAD

**Issue by fabinhojcr** [wll1rah/R43-Pro_handheld#1]
I have a question, the console system is emuelec 4.3, wouldn't it be possible to update to version 4.7 which is the most recent?

**Comment by josemarprete** [comment]
It must not be EmuELEC! There is no version 4.3 for rk3566, since support started in version 4.6-TEST for FireFly M2! And on the product box it says Emelec, and somewhere it says uELEC! It seems to be some franskstein system based on EmulationStation!

**Comment by fabinhojcr** [comment]
I hope someone dedicates themselves to a custom ROM cause this is a great console with a system that is absolute garbage.

**Comment by josemarprete** [comment]
Yes, a complete CFW like AmberELEC, ArkOS, Batocera, etc. would be great. It seems that there are attempts, but there are no effective results yet. On Discord, it is reported that Kobil managed to make EmuELEC work, but there are not many details and he has not made it available to the public. Did he manage to obtain the dtb? I hope he shares a working image, or at least the dtb, if he managed to extract it. On the other hand, these files made available here on this github already improve usability a little. For me, the most impactful thing was the fact that it changed the aspect ratio of the games to the one provided by the core. That already helps. In addition, I added folders for NeoGeo, Sega32x, Dreamcast and Supergrafx games. And the fact that we have the RetroArch menu. All of this made the system better. And the performance is very good! I used a translator!

**Comment by fabinhojcr** [comment]
Yes, the files made available here have greatly improved usability, thank u @wll1rah for that, I customized some things my way, updated cores, changed default cores, among other things, but the fact that I can't customize the front end or change the Retroarch settings is annoying.

**Comment by fejdraus** [comment]
Can you tell me if it is possible to change the Bios for PSX? I put in System as recommended in the instructions, but in Retroarch settings for PSX they still do not appear. Just like enabling the boot log for PSX doesn't help, it still doesn't appear.
