### ISSUE TITLE
R43 Pro SAVE DATA LOCATION

### ISSUE THREAD

**Issue by SailorArtema** [wll1rah/R43-Pro_handheld#3]
SO I was just wondering where are located the save files, save states or memory cards in this console folders? Anyone know how to make this console load PSX, GBA or any other console saves? I want to share my progress with this console with several games like Castlevania SOTN, Pokemon games and Final fantasy PSX games but I couldn't figure it out guys, hope you all know how to do it

Additionally, does somebody have luck making retroarch shaders or any other shaders work in this console?

**Comment by wll1rah** [comment]
Looks like I need to enable the save features in the retroarch.cfg file, I'll set to put the saves and save states in the content directory.  Sorry for that and thanks for letting me know about this and I'm glad people are using it so I can make it even better as time goes on.

**Comment by SailorArtema** [comment]
Ok just figured out how to do it some how with PSX and Gameboy working

i just renamed my (mcd & Sav) data files with same names and changed the exe code to: .SRM in the same folder as the game so 

it looked like this:

Pokemon FireRed (USA).SRM
it solved the problem itself, not converting nothing else is needed, I hope we can solve the PSX shders also as well as the GBA,  GBcolor and so on !

**Comment by wll1rah** [comment]
Okay updated the. quick menu to enable saves and save states and then will place them in the content directory and as stated above they will be saved with the srm extension or should be anyway.
